import type { AppProps } from "next/app";
import Head from "next/head";
import "../styles/globals.css";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "../firebase/firebase";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Loading from "../components/Loading";

function MyApp({ Component, pageProps }: AppProps) {
	const [user, loading, error] = useAuthState(auth);
	const router = useRouter();

	useEffect(() => {
		if (!loading && !user && router.pathname !== "/auth/login")
			router.push("/auth/login");
	}, [user, loading]);

	if (loading) {
		return (
			<div>
				<Loading></Loading>
			</div>
		);
	}
	return (
		<div>
			<Head>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Component {...pageProps} />
			</main>
		</div>
	);
}

export default MyApp;
